spring:
  application:
    name: rest

## PostgreSQL
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      connectionTimeout: 20000
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl