
CREATE TABLE IF NOT EXISTS users (
                                     id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username  VARCHAR(25) NOT NULL,
                                     email     VARCHAR(50) NOT NULL,
                                     password  VARCHAR(256) NOT NULL,
                                     level     INT DEFAULT 0 NOT NULL,
                                     streak  INT DEFAULT 0 NOT NULL,
                                     UNIQUE (username)
);

INSERT INTO users (username, email, password)
SELECT 'jojo', 'jojo@gmail.com', '{noop}password'
    WHERE NOT EXISTS (SELECT * FROM users WHERE ID=1);

