
CREATE TABLE IF NOT EXISTS questions (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic  VARCHAR(50) NOT NULL,
    difficulty  VARCHAR(20) NOT NULL,
    description  TEXT NOT NULL -- LaTeX format
    );

INSERT INTO questions (topic, difficulty, description)
SELECT 'arithmetic', 'easy', 'What is 2 + 2?'
    WHERE NOT EXISTS (SELECT * FROM questions WHERE ID=1);

INSERT INTO questions (topic, difficulty, description)
SELECT 'arithmetic', 'easy', 'What is 3 * 5?'
    WHERE NOT EXISTS (SELECT * FROM questions WHERE ID=2);


