CREATE TABLE IF NOT EXISTS streak_defs (
     id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name  VARCHAR(30) NOT NULL,
    freq VARCHAR(30) DEFAULT 'DAILY' NOT NULL
    );

INSERT INTO streak_defs (name, freq)
SELECT 'Problem of the Day', 'DAILY'
    WHERE NOT EXISTS (SELECT * FROM streak_defs WHERE ID=1);