CREATE TABLE IF NOT EXISTS streaks (
           id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           user_id  BIGINT NOT NULL,
           streak_id  BIGINT NOT NULL,
           count INT DEFAULT 0 NOT NULL,
           FOREIGN KEY(user_id)
               REFERENCES users(id)
               ON DELETE CASCADE,
           FOREIGN KEY(streak_id)
               REFERENCES streaks(id)
               ON DELETE CASCADE,
           UNIQUE (user_id, streak_id)
);

INSERT INTO streaks (user_id, streak_id, count)
SELECT 1, 1, 12
WHERE NOT EXISTS (SELECT * FROM streaks WHERE ID=1);